name: Deploy Model to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pip install huggingface_hub --upgrade

      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Deploy model to Hugging Face
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          REPO_USERNAME: Ebenezer-DS
        run: |
          git config --global user.email "ebenelomo01@gmail.com"
          git config --global user.name "Ebenezer-DS"
          git remote set-url origin https://${REPO_USERNAME}:${REPO_TOKEN}@github.com/${REPO_USERNAME}/CIFAR10_IMAGE_RECOGNITIION.git
          git push -f -u origin main --exclude=.github/workflows/
