name: Deploy Model to Hugging Face

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install huggingface_hub --upgrade

      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Deploy model to Hugging Face
        run: |
          git config --global user.email "ebenelomo01@gmail.com"
          git config --global user.name "Ebenezer-DS"
          cp -r CIFAR10_IMAGE_RECOGNITIION/* cifar10_image_recognition/
          cd cifar10_image_recognition
          git init
          git add .
          git commit -m "Upload model files"
          git remote add origin https://huggingface.co/datasets/Ebenevation/cifar10_image_recognition
          git push -u origin master
