name: Deploy Model to Hugging Face

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install huggingface_hub --upgrade

      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Clone repository
        run: git clone https://huggingface.co/datasets/Ebenevation/cifar10_image_recognition

      - name: Deploy model to Hugging Face
        run: |
          git config --global user.email "ebenelomo01@gmail.com"
          git config --global user.name "Ebenezer-DS"
          cd cifar10_image_recognition
          cp -r ../model_files/* .
          git add .
          git commit -m "Upload model files"
          git push
